export const categories = [
      "All Categories",
      "Electronics",
      "Fashion",
      "Books",
      "Sports",
      "Home",
      "Kitchen",
      "Beauty",
      "Health",
      "Grocery",
      "Mobiles",
      "Laptops",
      "Tablets",
      "Cameras",
      "Audio",
      "Gaming",
      "Furniture",
      "Appliances",
      "Automotive",
      "Baby",
      "Pets",
      "Jewelry",
      "Watches",
      "Footwear",
      "Bags",
      "Stationery",
      "Musical Instruments",
      "Movies",
      "Travel",
      "Tools",
    ];